### ISSUE TITLE
Changing page with browser navigation buttons

### ISSUE THREAD

**Issue by drewfoglesong** [TattMaylor/Marshall-University-Virtual-Tour#8]
In Chrome (haven't tested other browsers), hitting the 'back' arrow in the browser to return to the dashboard, then hitting the 'forward' arrow to go back to the tour results in an error and the picture fails to load.

**Comment by DLewis115** [comment]
This issue doesn't occur on Safari.

**Comment by drewfoglesong** [comment]
The issue also exists on firefox, but not edge. It blows up if you go back to the dashboard at all, even if you click the button

**Comment by DLewis115** [comment]
I believe its browser settings that are causing the issue with Firefox and Chrome. Change these settings and let me know what your results are. 

**Chrome Settings:**
Disable the setting "use Hardware Acceleration when available"
restart chrome

**Firefox Settings:**
Disable the setting "use Hardware Acceleration when available"
In the address bar, type about:config and press Return. 
Click "I Accept the risk"
Search for "webgl.disabled" and set to true
restart firefox

**Comment by drewfoglesong** [comment]
Update 2/14/2017 
Fixed the picture loading issue due to hardware acceleration. However, when the page reloads, the link arrows don't move when the picture is rotated. You can still click them.

**Comment by DLewis115** [comment]
Update 2/14/2017
Zooming in/out does not work properly after page reloads on chrome/firefox with hardware acceleration turned on.

**Comment by drewfoglesong** [comment]
Closed via 74ead853ad11c5466a6d0cc4cf197cd5d94b3581
